### ISSUE TITLE
The compiler jar file is not generated 

### ISSUE THREAD

**Issue by transistors** [drasil/BinaryNotes#2]
Hi,
BinaryNotes version 1.6 does not include the binarycompiler-1.6. jar file. this is required by the binarycompiler cmd and sh files. I have managed to generate it myself however it would be good if this is made available in the zip file for others too! 
I am attaching the complied files that is needed for running the compiler! The zipe file should be extracted to ...\BNCompiler\src\main\scripts

[bncompiler-1.6-dist.zip](https://github.com/drasil/BinaryNotes/files/156111/bncompiler-1.6-dist.zip)

**Comment by drasil** [comment]
Hello, I do not plan to provide a downloadable binary distribution. I even think that it is not a common Github practise. The modus operandi here is to download the sources (or better clone the repository) and compile the project by yourself. This is a standard Maven project, so building the project is really easy - you just need to run "mvn package" or "mvn install" depending on what exactly do you want. Perhaps I can add an instruction to the README file.

**Comment by transistors** [comment]
Hi Drasil, no problem This is fine. Thank you.

I have picked up some issues. I will be opening some tickets for them I hope you can have a look.

Thanks in advance
