### ISSUE TITLE
Compiled 1.6 bncompiler files

### ISSUE THREAD

**Issue by etempm** [drasil/BinaryNotes#4]
Hi,
I am using c# and no info about java projects. So I can not compile 1.6 compiler source code to assembly. I s it possible to add compiled compiler to download area. thanks.

**Comment by drasil** [comment]
A compiled binary was added to the latest release

**Comment by etempm** [comment]
Sory. I can not found bncompiler.jar file in BinaryNotes-master folder. Can you help me ? Thanks.
